let words1 = [
  { word: "hello", translation: "salom" },
  { word: "world", translation: "dunyo" },
  { word: "help", translation: "yordam" },
  { word: "hero", translation: "qahramon" },
  { word: "house", translation: "uy" },
  { word: "heart", translation: "yurak" },
  { word: "hope", translation: "umid" },
  { word: "hurry", translation: "shoshilish" },
  { word: "hard", translation: "qiyin" },
  { word: "habit", translation: "odat" },
  { word: "high", translation: "baland" },
  { word: "hold", translation: "ushlamoq" },
  { word: "home", translation: "uy" },
  { word: "ability", translation: "qobiliyat" },
  { word: "alone", translation: "yolg'iz" },
  { word: "again", translation: "yana" },
  { word: "add", translation: "qo'shmoq" },
  { word: "food", translation: "ovqat" },
  { word: "school", translation: "maktab" },
  { word: "computer", translation: "kompyuter" },
  { word: "phone", translation: "telefon" },
  { word: "music", translation: "musiqa" },
  { word: "movie", translation: "kino" },
  { word: "travel", translation: "sayohat" },
  { word: "language", translation: "til" },
  { word: "love", translation: "sevgi" },
  { word: "peace", translation: "tinchlik" },
  { word: "dream", translation: "tush" },
  { word: "play", translation: "o'ynash" },
  { word: "run", translation: "yugurmoq" },
  { word: "walk", translation: "yurmoq" },
  { word: "sleep", translation: "uxlamoq" },
  { word: "eat", translation: "yemoq" },
  { word: "drink", translation: "ichmoq" },
  { word: "write", translation: "yozmoq" },
  { word: "read", translation: "o'qimoq" },
  { word: "listen", translation: "tinglamoq" },
  { word: "speak", translation: "gapirmoq" },
  { word: "think", translation: "o'ylamoq" },
  { word: "learn", translation: "o'rganmoq" },
  { word: "teach", translation: "o'rgatmoq" },
  { word: "build", translation: "qurmoq" },
  { word: "create", translation: "yaratmoq" },
  { word: "imagine", translation: "tasavvur qilmoq" },
  { word: "strong", translation: "kuchli" },
  { word: "weak", translation: "zaif" },
  { word: "fast", translation: "tez" },
  { word: "slow", translation: "sekin" },
  { word: "bright", translation: "yorqin" },
  { word: "dark", translation: "qorong'i" },
  { word: "young", translation: "yosh" },
  { word: "old", translation: "qari" },
  { word: "beautiful", translation: "chiroyli" },
  { word: "ugly", translation: "xunuk" },
  { word: "happy", translation: "xursand" },
  { word: "sad", translation: "xafa" },
  { word: "angry", translation: "jahldor" },
  { word: "kind", translation: "mehribon" },
  { word: "funny", translation: "kulgili" },
  { word: "clever", translation: "aqlli" },
  { word: "brave", translation: "jasur" },
  { word: "rich", translation: "boy" },
  { word: "poor", translation: "kambag'al" },
  { word: "clean", translation: "toza" },
  { word: "dirty", translation: "iflos" },
  { word: "easy", translation: "oson" },
  { word: "difficult", translation: "qiyin" },
  { word: "big", translation: "katta" },
  { word: "small", translation: "kichik" },
  { word: "long", translation: "uzun" },
  { word: "short", translation: "qisqa" },
  { word: "wide", translation: "keng" },
  { word: "narrow", translation: "tor" },
  { word: "soft", translation: "yumshoq" },
  { word: "heavy", translation: "og'ir" },
  { word: "one", translation: "bir" },
  { word: "two", translation: "ikki" },
  { word: "three", translation: "uch" },
  { word: "four", translation: "to'rt" },
  { word: "five", translation: "besh" },
  { word: "six", translation: "olti" },
  { word: "seven", translation: "yetti" },
  { word: "eight", translation: "sakkiz" },
  { word: "nine", translation: "to'qqiz" },
  { word: "ten", translation: "o'n" },
  { word: "twenty", translation: "yigirma" },
  { word: "fifty", translation: "ellik" },
  { word: "hundred", translation: "yuz" },
  { word: "thousand", translation: "ming" },
  { word: "red", translation: "qizil" },
  { word: "blue", translation: "ko'k" },
  { word: "green", translation: "yashil" },
  { word: "yellow", translation: "sariq" },
  { word: "white", translation: "oq" },
  { word: "black", translation: "qora" },
  { word: "gray", translation: "kulrang" },
  { word: "pink", translation: "pushti" },
  { word: "purple", translation: "siyohrang" },
  { word: "brown", translation: "jigarrang" },
  { word: "orange", translation: "apelsin rang" },
  { word: "cat", translation: "mushuk" },
  { word: "dog", translation: "kuchuk" },
  { word: "bird", translation: "qush" },
  { word: "cow", translation: "sigir" },
  { word: "horse", translation: "ot" },
  { word: "sheep", translation: "qo'y" },
  { word: "goat", translation: "echki" },
  { word: "duck", translation: "o'rdak" },
  { word: "pig", translation: "cho'chqa" },
  { word: "rabbit", translation: "quyon" },
  { word: "lion", translation: "sher" },
  { word: "tiger", translation: "yo'lbars" },
  { word: "bear", translation: "ayiq" },
  { word: "elephant", translation: "fil" },
  { word: "giraffe", translation: "jirafa" },
  { word: "monkey", translation: "maymun" },
  { word: "snake", translation: "ilon" },
  { word: "tree", translation: "daraxt" },
  { word: "flower", translation: "gul" },
  { word: "grass", translation: "o't" },
  { word: "sun", translation: "quyosh" },
  { word: "moon", translation: "oy" },
  { word: "star", translation: "yulduz" },
  { word: "sky", translation: "osmon" },
  { word: "cloud", translation: "bulut" },
  { word: "rain", translation: "yomg'ir" },
  { word: "snow", translation: "qor" },
  { word: "wind", translation: "shamol" },
  { word: "storm", translation: "bo'ron" },
  { word: "fire", translation: "olov" },
  { word: "water", translation: "suv" },
  { word: "earth", translation: "yer" },
  { word: "stone", translation: "tosh" },
  { word: "sand", translation: "qum" },
  { word: "mountain", translation: "tog'" },
  { word: "river", translation: "daryo" },
  { word: "lake", translation: "ko'l" },
  { word: "sea", translation: "dengiz" },
  { word: "ocean", translation: "okean" },
  { word: "forest", translation: "o'rmon" },
  { word: "desert", translation: "cho'l" },
  { word: "city", translation: "shahar" },
  { word: "village", translation: "qishloq" },
  { word: "street", translation: "ko'cha" },
  { word: "road", translation: "yo'l" },
  { word: "bridge", translation: "ko'prik" },
  { word: "building", translation: "bino" },
  { word: "station", translation: "stantsiya" },
  { word: "airport", translation: "aeroport" },
  { word: "hotel", translation: "mehmonxona" },
  { word: "restaurant", translation: "restoran" },
  { word: "cafe", translation: "kafe" },
  { word: "bank", translation: "bank" },
  { word: "post", translation: "pochta" },
  { word: "museum", translation: "muzey" },
  { word: "park", translation: "park" },
  { word: "garden", translation: "bog'" },
  { word: "zoo", translation: "hayvonot bog'i" },
  { word: "cinema", translation: "kinoteatr" },
  { word: "theater", translation: "teatr" },
  { word: "library", translation: "kutubxona" },
  { word: "university", translation: "universitet" },
  { word: "college", translation: "kollej" },
  { word: "office", translation: "ofis" },
  { word: "factory", translation: "zavod" },
  { word: "farm", translation: "ferma" },
  { word: "apartment", translation: "kvartira" },
  { word: "room", translation: "xona" },
  { word: "kitchen", translation: "oshxona" },
  { word: "bathroom", translation: "hammom" },
  { word: "bedroom", translation: "yotoqxona" },
  { word: "living room", translation: "mehmonxona" },
  { word: "door", translation: "eshik" },
  { word: "window", translation: "deraza" },
  { word: "wall", translation: "devor" },
  { word: "floor", translation: "pol" },
  { word: "ceiling", translation: "shift" },
  { word: "roof", translation: "tom" },
  { word: "stairs", translation: "narvon" },
  { word: "table", translation: "stol" },
  { word: "chair", translation: "stul" },
  { word: "bed", translation: "karavot" },
  { word: "sofa", translation: "divan" },
  { word: "cupboard", translation: "javon" },
  { word: "shelf", translation: "reja" },
  { word: "mirror", translation: "oyna" },
  { word: "lamp", translation: "chiroq" },
  { word: "picture", translation: "rasm" },
  { word: "carpet", translation: "gilam" },
  { word: "blanket", translation: "yopinchiq" },
  { word: "pillow", translation: "yostiq" },
  { word: "towel", translation: "sochiq" },
  { word: "clothes", translation: "kiyim" },
  { word: "shirt", translation: "ko'ylak" },
  { word: "t-shirt", translation: "futbolka" },
  { word: "pants", translation: "shim" },
  { word: "jeans", translation: "jinsi" },
  { word: "dress", translation: "ko'ylak" },
  { word: "skirt", translation: "yubka" },
  { word: "jacket", translation: "kurtka" },
  { word: "coat", translation: "palto" },
  { word: "hat", translation: "shlyapa" },
  { word: "cap", translation: "kepka" },
  { word: "shoes", translation: "poyabzal" },
  { word: "sneakers", translation: "krossovka" },
  { word: "boots", translation: "etik" },
  { word: "socks", translation: "paypoq" },
  { word: "underwear", translation: "ichki kiyim" },
  { word: "gloves", translation: "qo'lqop" },
  { word: "scarf", translation: "sharf" },
  { word: "bag", translation: "sumka" },
  { word: "wallet", translation: "hamyon" },
  { word: "jewelry", translation: "zargarlik buyumlari" },
  { word: "ring", translation: "uzuk" },
  { word: "necklace", translation: "munchoq" },
  { word: "earrings", translation: "zirak" },
  { word: "glasses", translation: "ko'zoynak" },
  { word: "umbrella", translation: "soyabon" },
  { word: "book", translation: "kitob" },
  { word: "notebook", translation: "daftar" },
  { word: "pen", translation: "ruchka" },
  { word: "pencil", translation: "qalam" },
  { word: "eraser", translation: "o'chirgich" },
  { word: "ruler", translation: "chizg'ich" },
  { word: "scissors", translation: "qaychi" },
  { word: "glue", translation: "yelim" },
  { word: "paper", translation: "qog'oz" },
  { word: "envelope", translation: "konvert" },
  { word: "stamp", translation: "marka" },
  { word: "package", translation: "paket" },
  { word: "box", translation: "quti" },
  { word: "bottle", translation: "shisha" },
  { word: "cup", translation: "fincan" },
  { word: "plate", translation: "likopcha" },
  { word: "bowl", translation: "kosa" },
  { word: "fork", translation: "vilka" },
  { word: "spoon", translation: "qoshiq" },
  { word: "knife", translation: "pichoq" },
  { word: "pan", translation: "tava" },
  { word: "pot", translation: "qozon" },
  { word: "microwave", translation: "mikroto'lqinli pech" },
  { word: "refrigerator", translation: "muzlatgich" },
  { word: "oven", translation: "pech" },
  { word: "stove", translation: "pechka" },
  { word: "sink", translation: "rakovina" },
  { word: "washing machine", translation: "kir yuvish mashinasi" },
  { word: "vacuum cleaner", translation: "changyutgich" },
  { word: "iron", translation: "dazmol" },
  { word: "fan", translation: "ventilyator" },
  { word: "heater", translation: "isitgich" },
  { word: "air conditioner", translation: "konditsioner" },
  { word: "light", translation: "yorug'lik" },
  { word: "bulb", translation: "lampa" },
  { word: "battery", translation: "batareya" },
  { word: "laptop", translation: "noutbuk" },
  { word: "tablet", translation: "planshet" },
  { word: "television", translation: "televizor" },
  { word: "radio", translation: "radio" },
  { word: "camera", translation: "kamera" },
  { word: "headphones", translation: "naushnik" },
  { word: "speaker", translation: "karnay" },
  { word: "charger", translation: "zaryadlovchi" },
  { word: "bicycle", translation: "velosiped" },
  { word: "car", translation: "mashina" },
  { word: "bus", translation: "avtobus" },
  { word: "train", translation: "poezd" },
  { word: "plane", translation: "samolyot" },
  { word: "ship", translation: "kema" },
  { word: "taxi", translation: "taksi" },
  { word: "motorcycle", translation: "mototsikl" },
  { word: "truck", translation: "yuk mashinasi" },
  { word: "police car", translation: "militsiya mashinasi" },
  { word: "fire truck", translation: "o't o'chirish mashinasi" },
  { word: "wheel", translation: "g'ildirak" },
  { word: "tire", translation: "shina" },
  { word: "engine", translation: "dvigatel" },
  { word: "key", translation: "kalit" },
  { word: "lock", translation: "qulf" },
  { word: "tool", translation: "asbob" },
  { word: "hammer", translation: "bolg'a" },
  { word: "screwdriver", translation: "sharnix" },
  { word: "wrench", translation: "gaykacha" },
  { word: "nail", translation: "mix" },
  { word: "screw", translation: "vint" },
  { word: "rope", translation: "arqon" },
  { word: "ladder", translation: "narvon" },
  { word: "paint", translation: "bo'yoq" },
  { word: "brush", translation: "cho'tka" },
  { word: "wood", translation: "yog'och" },
  { word: "metal", translation: "metall" },
  { word: "plastic", translation: "plastik" },
  { word: "glass", translation: "shisha" },
  { word: "rubber", translation: "rezina" },
  { word: "leather", translation: "charm" },
  { word: "fabric", translation: "mato" },
  { word: "cotton", translation: "paxta" },
  { word: "wool", translation: "jun" },
  { word: "silk", translation: "ipak" },
  { word: "zipper", translation: "zanjir" },
  { word: "needle", translation: "igna" },
  { word: "thread", translation: "ip" },
  { word: "money", translation: "pul" },
  { word: "coin", translation: "tanga" },
  { word: "bill", translation: "banknota" },
  { word: "credit card", translation: "kredit karta" },
  { word: "receipt", translation: "chek" },
  { word: "price", translation: "narx" },
  { word: "cost", translation: "xarajat" },
  { word: "expensive", translation: "qimmat" },
  { word: "cheap", translation: "arzon" },
  { word: "free", translation: "bepul" },
  { word: "buy", translation: "sotib olmoq" },
  { word: "sell", translation: "sotmoq" },
  { word: "shop", translation: "sotib olish" },
  { word: "store", translation: "do'kon" },
  { word: "market", translation: "bozor" },
  { word: "sale", translation: "sotuv" },
  { word: "discount", translation: "chegirma" },
  { word: "size", translation: "o'lcham" },
  { word: "color", translation: "rang" },
  { word: "style", translation: "uslub" },
  { word: "fashion", translation: "moda" },
  { word: "brand", translation: "brend" },
  { word: "quality", translation: "sifat" },
  { word: "quantity", translation: "miqdor" },
  { word: "piece", translation: "bo'lak" },
  { word: "pair", translation: "juft" },
  { word: "dozen", translation: "dast" },
  { word: "kilogram", translation: "kilogram" },
  { word: "liter", translation: "litr" },
  { word: "meter", translation: "metr" },
  { word: "centimeter", translation: "santimetr" },
  { word: "kilometer", translation: "kilometr" },
  { word: "mile", translation: "milya" },
  { word: "inch", translation: "dyuym" },
  { word: "foot", translation: "fut" },
  { word: "pound", translation: "funt" },
  { word: "ounce", translation: "untsiya" },
  { word: "temperature", translation: "harorat" },
  { word: "degree", translation: "daraja" },
  { word: "weather", translation: "ob-havo" },
  { word: "sunny", translation: "quyoshli" },
  { word: "cloudy", translation: "bulutli" },
  { word: "rainy", translation: "yomg'irli" },
  { word: "snowy", translation: "qorli" },
  { word: "windy", translation: "shamolli" },
  { word: "foggy", translation: "tumanli" },
  { word: "stormy", translation: "bo'ronli" },
  { word: "hot", translation: "issiq" },
  { word: "warm", translation: "iliq" },
  { word: "cool", translation: "sovuq" },
  { word: "cold", translation: "sovuq" },
  { word: "dry", translation: "quruq" },
  { word: "wet", translation: "ho'l" },
  { word: "humid", translation: "nam" },
  { word: "season", translation: "fasl" },
  { word: "spring", translation: "bahor" },
  { word: "summer", translation: "yoz" },
  { word: "autumn", translation: "kuz" },
  { word: "winter", translation: "qish" },
  { word: "month", translation: "oy" },
  { word: "January", translation: "yanvar" },
  { word: "February", translation: "fevral" },
  { word: "March", translation: "mart" },
  { word: "April", translation: "aprel" },
  { word: "May", translation: "may" },
  { word: "June", translation: "iyun" },
  { word: "July", translation: "iyul" },
  { word: "August", translation: "avgust" },
  { word: "September", translation: "sentabr" },
  { word: "October", translation: "oktabr" },
  { word: "November", translation: "noyabr" },
  { word: "December", translation: "dekabr" },
  { word: "week", translation: "hafta" },
  { word: "Monday", translation: "dushanba" },
  { word: "Tuesday", translation: "seshanba" },
  { word: "Wednesday", translation: "chorshanba" },
  { word: "Thursday", translation: "payshanba" },
  { word: "Friday", translation: "juma" },
  { word: "Saturday", translation: "shanba" },
  { word: "Sunday", translation: "yakshanba" },
  { word: "day", translation: "kun" },
  { word: "morning", translation: "ertalab" },
  { word: "afternoon", translation: "kunduz" },
  { word: "evening", translation: "kechqurun" },
  { word: "night", translation: "tun" },
  { word: "midnight", translation: "yarim tun" },
  { word: "dawn", translation: "tong" },
  { word: "dusk", translation: "shom" },
  { word: "time", translation: "vaqt" },
  { word: "hour", translation: "soat" },
  { word: "minute", translation: "daqiqa" },
  { word: "second", translation: "soniya" },
  { word: "clock", translation: "soat" },
  { word: "watch", translation: "soat" },
  { word: "calendar", translation: "taqvim" },
  { word: "year", translation: "yil" },
  { word: "century", translation: "asr" },
  { word: "past", translation: "o'tmish" },
  { word: "present", translation: "hozir" },
  { word: "future", translation: "kelajak" },
  { word: "now", translation: "hozir" },
  { word: "later", translation: "keyin" },
  { word: "soon", translation: "tez orada" },
  { word: "early", translation: "erta" },
  { word: "late", translation: "kech" },
  { word: "always", translation: "doimo" },
  { word: "often", translation: "tez-tez" },
  { word: "sometimes", translation: "ba'zan" },
  { word: "rarely", translation: "kamdan-kam" },
  { word: "never", translation: "hech qachon" },
  { word: "today", translation: "bugun" },
  { word: "yesterday", translation: "kecha" },
  { word: "tomorrow", translation: "ertaga" },
  { word: "tonight", translation: "bugun kechqurun" },
  { word: "next", translation: "keyingi" },
  { word: "last", translation: "o'tgan" },
  { word: "birthday", translation: "tug'ilgan kun" },
  { word: "holiday", translation: "bayram" },
  { word: "vacation", translation: "ta'til" },
  { word: "party", translation: "ziyofat" },
  { word: "meeting", translation: "uchrashuv" },
  { word: "appointment", translation: "uchrashuv" },
  { word: "schedule", translation: "jadval" },
  { word: "plan", translation: "reja" },
  { word: "event", translation: "hodisa" },
  { word: "celebration", translation: "tantanali marosim" },
  { word: "ceremony", translation: "marosim" },
  { word: "tradition", translation: "an'ana" },
  { word: "custom", translation: "odat" },
  { word: "culture", translation: "madaniyat" },
  { word: "religion", translation: "din" },
  { word: "god", translation: "xudo" },
  { word: "church", translation: "cherkov" },
  { word: "mosque", translation: "masjid" },
  { word: "temple", translation: "ibodatxona" },
  { word: "prayer", translation: "ibodat" },
  { word: "belief", translation: "e'tiqod" },
  { word: "faith", translation: "imon" },
  { word: "charity", translation: "xayriya" },
  { word: "volunteer", translation: "ko'ngilli" },
  { word: "community", translation: "jamiyat" },
  { word: "society", translation: "jamiyat" },
  { word: "government", translation: "hukumat" },
  { word: "president", translation: "prezident" },
  { word: "minister", translation: "vazir" },
  { word: "mayor", translation: "hokim" },
  { word: "leader", translation: "rahbar" },
  { word: "politics", translation: "siyosat" },
  { word: "law", translation: "qonun" },
  { word: "right", translation: "huquq" },
  { word: "duty", translation: "burch" },
  { word: "vote", translation: "ovoz berish" },
  { word: "election", translation: "saylov" },
  { word: "campaign", translation: "kampaniya" },
  { word: "protest", translation: "norozilik" },
  { word: "strike", translation: "ish tashlash" },
  { word: "war", translation: "urush" },
  { word: "army", translation: "armiya" },
  { word: "soldier", translation: "askar" },
  { word: "officer", translation: "ofitser" },
  { word: "general", translation: "general" },
  { word: "weapon", translation: "qurol" },
  { word: "gun", translation: "miltoq" },
  { word: "bomb", translation: "bomba" },
  { word: "attack", translation: "hujum" },
  { word: "defense", translation: "himoya" },
  { word: "victory", translation: "g'alaba" },
  { word: "defeat", translation: "mag'lubiyat" },
  { word: "prison", translation: "qamoqxona" },
  { word: "criminal", translation: "jinoyatchi" },
  { word: "police", translation: "politsiya" },
  { word: "judge", translation: "sudya" },
  { word: "court", translation: "sud" },
  { word: "witness", translation: "guvoh" },
  { word: "crime", translation: "jinoyat" },
  { word: "murder", translation: "qotillik" },
  { word: "theft", translation: "o'g'rilik" },
  { word: "robbery", translation: "talonchilik" },
  { word: "fraud", translation: "firibgarlik" },
  { word: "violence", translation: "zo'ravonlik" },
  { word: "punishment", translation: "jazo" },
  { word: "fine", translation: "jarima" },
  { word: "life", translation: "hayot" },
  { word: "health", translation: "salomatlik" },
  { word: "illness", translation: "kasallik" },
  { word: "disease", translation: "kasallik" },
  { word: "pain", translation: "og'riq" },
  { word: "fever", translation: "isitma" },
  { word: "headache", translation: "bosh og'rig'i" },
  { word: "stomachache", translation: "qorin og'rig'i" },
  { word: "cough", translation: "yo'tal" },
  { word: "flu", translation: "gripp" },
  { word: "allergy", translation: "allergiya" },
  { word: "medicine", translation: "dori" },
  { word: "pill", translation: "tabletka" },
  { word: "vaccine", translation: "vaksina" },
  { word: "nurse", translation: "hamshira" },
  { word: "hospital", translation: "kasalxona" },
  { word: "clinic", translation: "klinika" },
  { word: "pharmacy", translation: "dorixona" },
  { word: "ambulance", translation: "tez yordam" },
  { word: "operation", translation: "operatsiya" },
  { word: "treatment", translation: "davolash" },
  { word: "recovery", translation: "tuzalish" },
  { word: "death", translation: "o'lim" },
  { word: "birth", translation: "tug'ilish" },
  { word: "pregnant", translation: "homilador" },
  { word: "baby", translation: "chaqaloq" },
  { word: "child", translation: "bola" },
  { word: "boy", translation: "o'g'il bola" },
  { word: "girl", translation: "qiz bola" },
  { word: "teenager", translation: "o'smir" },
  { word: "adult", translation: "katta" },
  { word: "man", translation: "erkak" },
  { word: "woman", translation: "ayol" },
  { word: "husband", translation: "er" },
  { word: "wife", translation: "xotin" },
  { word: "father", translation: "ota" },
  { word: "mother", translation: "ona" },
  { word: "son", translation: "o'g'il" },
  { word: "daughter", translation: "qiz" },
  { word: "brother", translation: "aka" },
  { word: "sister", translation: "opa" },
  { word: "grandfather", translation: "bobo" },
  { word: "grandmother", translation: "buvi" },
  { word: "uncle", translation: "amaki" },
  { word: "aunt", translation: "xola" },
  { word: "cousin", translation: "amakivachcha" },
  { word: "nephew", translation: "jiyan" },
  { word: "niece", translation: "jiyan" },
  { word: "family", translation: "oila" },
  { word: "relative", translation: "qarindosh" },
  { word: "friend", translation: "do'st" },
  { word: "neighbor", translation: "qo'shni" },
  { word: "colleague", translation: "hamkasb" },
  { word: "boss", translation: "boshliq" },
  { word: "employee", translation: "xodim" },
  { word: "worker", translation: "ishchi" },
  { word: "farmer", translation: "fermer" },
  { word: "teacher", translation: "o'qituvchi" },
  { word: "student", translation: "talaba" },
  { word: "doctor", translation: "shifokor" },
  { word: "engineer", translation: "muhandis" },
  { word: "lawyer", translation: "advokat" },
  { word: "artist", translation: "rassom" },
  { word: "musician", translation: "musiqachi" },
  { word: "actor", translation: "aktyor" },
  { word: "writer", translation: "yozuvchi" },
  { word: "journalist", translation: "jurnalist" },
  { word: "reporter", translation: "reportyor" },
  { word: "photographer", translation: "fotograf" },
  { word: "cook", translation: "oshpaz" },
  { word: "waiter", translation: "ofitsiant" },
  { word: "driver", translation: "haydovchi" },
  { word: "pilot", translation: "uchuvchi" },
  { word: "captain", translation: "kapitan" },
  { word: "sailor", translation: "dengizchi" },
  { word: "police officer", translation: "politsiyachi" },
  { word: "firefighter", translation: "o't o'chiruvchi" },
  { word: "builder", translation: "quruvchi" },
  { word: "carpenter", translation: "duradgor" },
  { word: "plumber", translation: "suvchi" },
  { word: "electrician", translation: "elektrikchi" },
  { word: "mechanic", translation: "mexanik" },
  { word: "hairdresser", translation: "sartarosh" },
  { word: "barber", translation: "sartarosh" },
  { word: "tailor", translation: "tikuvchi" },
  { word: "cleaner", translation: "tozalovchi" },
  { word: "gardener", translation: "bog'bon" },
  { word: "job", translation: "ish" },
  { word: "work", translation: "ish" },
  { word: "career", translation: "karera" },
  { word: "profession", translation: "kasb" },
  { word: "salary", translation: "maosh" },
  { word: "wage", translation: "ish haqi" },
  { word: "saxophone", translation: "saksofon" },
  { word: "guitar", translation: "gitara" },
  { word: "piano", translation: "pianino" },
  { word: "drum", translation: "baraban" },
  { word: "violin", translation: "skripka" },
  { word: "orchestra", translation: "orkestr" },
  { word: "concert", translation: "konsert" },
  { word: "album", translation: "albom" },
  { word: "melody", translation: "kuy" },
  { word: "rhythm", translation: "ritm" },
  { word: "dance", translation: "raqs" },
  { word: "singer", translation: "qo'shiqchi" },
  { word: "sports", translation: "sport" },
  { word: "football", translation: "futbol" },
  { word: "basketball", translation: "basketbol" },
  { word: "tennis", translation: "tennis" },
  { word: "volleyball", translation: "voleybol" },
  { word: "swimming", translation: "suzish" },
  { word: "running", translation: "yugurish" },
  { word: "jumping", translation: "sakrash" },
  { word: "climbing", translation: "tirmashish" },
  { word: "skiing", translation: "chang'i" },
  { word: "skating", translation: "konki" },
  { word: "surfing", translation: "serfinq" },
  { word: "diving", translation: "sho'ng'ish" },
  { word: "hiking", translation: "piyoda yurish" },
  { word: "camping", translation: "kemping" },
  { word: "fishing", translation: "baliq ovlash" },
  { word: "hunting", translation: "ov qilish" },
  { word: "chess", translation: "shaxmat" },
  { word: "cards", translation: "qarta" },
  { word: "dice", translation: "zar" },
  { word: "puzzle", translation: "boshqotirma" },
  { word: "game", translation: "o'yin" },
  { word: "toy", translation: "o'yinchoq" },
  { word: "doll", translation: "qo'g'irchoq" },
  { word: "ball", translation: "koptok" },
  { word: "science", translation: "fan" },
  { word: "mathematics", translation: "matematika" },
  { word: "physics", translation: "fizika" },
  { word: "chemistry", translation: "kimyo" },
  { word: "biology", translation: "biologiya" },
  { word: "geography", translation: "geografiya" },
  { word: "history", translation: "tarix" },
  { word: "literature", translation: "adabiyot" },
  { word: "art", translation: "san'at" },
  { word: "poetry", translation: "she'riyat" },
  { word: "novel", translation: "roman" },
  { word: "story", translation: "hikoya" },
  { word: "fairy tale", translation: "ertak" },
  { word: "legend", translation: "afsona" },
  { word: "myth", translation: "mif" },
  { word: "author", translation: "muallif" },
  { word: "reader", translation: "kitobxon" },
  { word: "publisher", translation: "nashriyot" },
  { word: "editor", translation: "muharrir" },
  { word: "newspaper", translation: "gazeta" },
  { word: "magazine", translation: "jurnal" },
  { word: "article", translation: "maqola" },
  { word: "report", translation: "hisobot" },
  { word: "letter", translation: "xat" },
  { word: "email", translation: "elektron pochta" },
  { word: "website", translation: "veb-sayt" },
  { word: "internet", translation: "internet" },
  { word: "network", translation: "tarmoq" },
  { word: "software", translation: "dasturiy ta'minot" },
  { word: "hardware", translation: "qurilma" },
  { word: "keyboard", translation: "klaviatura" },
  { word: "mouse", translation: "sichqoncha" },
  { word: "screen", translation: "ekran" },
  { word: "printer", translation: "printer" },
  { word: "scanner", translation: "skaner" },
  { word: "cable", translation: "kabel" },
  { word: "wire", translation: "sim" },
  { word: "signal", translation: "signal" },
  { word: "connection", translation: "ulanish" },
  { word: "password", translation: "parol" },
  { word: "username", translation: "foydalanuvchi nomi" },
  { word: "account", translation: "hisob" },
  { word: "profile", translation: "profil" },
  { word: "message", translation: "xabar" },
  { word: "chat", translation: "suhbat" },
  { word: "video", translation: "video" },
  { word: "audio", translation: "audio" },
  { word: "image", translation: "rasm" },
  { word: "file", translation: "fayl" },
  { word: "folder", translation: "papka" },
  { word: "document", translation: "hujjat" },
  { word: "presentation", translation: "taqdimot" },
  { word: "spreadsheet", translation: "elektron jadval" },
  { word: "database", translation: "ma'lumotlar bazasi" },
  { word: "program", translation: "dastur" },
  { word: "application", translation: "ilova" },
  { word: "system", translation: "tizim" },
  { word: "update", translation: "yangilash" },
  { word: "download", translation: "yuklab olish" },
  { word: "upload", translation: "yuklash" },
  { word: "install", translation: "o'rnatish" },
  { word: "uninstall", translation: "o'chirish" },
  { word: "restart", translation: "qayta ishga tushirish" },
  { word: "shutdown", translation: "o'chirish" },
  { word: "backup", translation: "zaxira nusxa" },
  { word: "restore", translation: "tiklash" },
  { word: "format", translation: "formatlash" },
  { word: "copy", translation: "nusxa olish" },
  { word: "paste", translation: "joylash" },
  { word: "cut", translation: "kesish" },
  { word: "delete", translation: "o'chirish" },
  { word: "save", translation: "saqlash" },
  { word: "search", translation: "qidirish" },
  { word: "find", translation: "topish" },
  { word: "replace", translation: "almashtirish" },
  { word: "share", translation: "ulashish" },
  { word: "settings", translation: "sozlamalar" },
  { word: "preferences", translation: "afzalliklar" },
  { word: "options", translation: "variantlar" },
  { word: "menu", translation: "menyu" },
  { word: "toolbar", translation: "asboblar paneli" },
  { word: "icon", translation: "belgi" },
  { word: "button", translation: "tugma" },
  { word: "link", translation: "havola" },
  { word: "apple", translation: "olma" },
  { word: "banana", translation: "banan" },
  { word: "grape", translation: "uzum" },
  { word: "strawberry", translation: "qulupnay" },
  { word: "peach", translation: "shaftoli" },
  { word: "pear", translation: "nok" },
  { word: "cherry", translation: "gilos" },
  { word: "watermelon", translation: "tarvuz" },
  { word: "melon", translation: "qovun" },
  { word: "lemon", translation: "limon" },
  { word: "pineapple", translation: "ananas" },
  { word: "coconut", translation: "kokos" },
  { word: "mango", translation: "mango" },
  { word: "pomegranate", translation: "anor" },
  { word: "fig", translation: "anjir" },
  { word: "date", translation: "xurmo" },
  { word: "kiwi", translation: "kivi" },
  { word: "avocado", translation: "avakado" },
  { word: "eggplant", translation: "baqlajon" },
  { word: "cucumber", translation: "bodring" },
  { word: "tomato", translation: "pomidor" },
  { word: "potato", translation: "kartoshka" },
  { word: "onion", translation: "piyoz" },
  { word: "garlic", translation: "sarimsoq" },
  { word: "carrot", translation: "sabzi" },
  { word: "cabbage", translation: "karam" },
  { word: "mushroom", translation: "qo'ziqorin" },
  { word: "corn", translation: "makkajo'xori" },
  { word: "pea", translation: "noxat" },
  { word: "bean", translation: "loviya" },
  { word: "lentil", translation: "yasmiq" },
  { word: "rice", translation: "guruch" },
  { word: "bread", translation: "non" },
  { word: "butter", translation: "saryog'" },
  { word: "cheese", translation: "pishloq" },
  { word: "egg", translation: "tuxum" },
  { word: "meat", translation: "go'sht" },
  { word: "beef", translation: "mol go'shti" },
  { word: "chicken", translation: "tovuq go'shti" },
  { word: "lamb", translation: "qo'y go'shti" },
  { word: "fish", translation: "baliq" },
  { word: "sausage", translation: "kolbasa" },
  { word: "honey", translation: "asal" },
  { word: "jam", translation: "murabbo" },
  { word: "salt", translation: "tuz" },
  { word: "sugar", translation: "shakar" },
  { word: "pepper", translation: "murch" },
  { word: "oil", translation: "yog'" },
  { word: "vinegar", translation: "sirka" },
  { word: "flour", translation: "un" },
  { word: "soup", translation: "sho'rva" },
  { word: "salad", translation: "salat" },
  { word: "cake", translation: "tort" },
  { word: "cookie", translation: "pechene" },
  { word: "chocolate", translation: "shokolad" },
  { word: "candy", translation: "konfet" },
  { word: "ice cream", translation: "muzqaymoq" },
  { word: "tea", translation: "choy" },
  { word: "coffee", translation: "kofe" },
  { word: "milk", translation: "sut" },
  { word: "juice", translation: "sharbat" },
  { word: "beer", translation: "pivo" },
  { word: "wine", translation: "vino" },
  { word: "vodka", translation: "aqaraq" },
  { word: "whiskey", translation: "viski" },
  { word: "cognac", translation: "konyak" },
  { word: "champagne", translation: "shampan" },
  { word: "cocktail", translation: "kokteyl" },
  { word: "lemonade", translation: "limonad" },
  { word: "mineral water", translation: "mineral suv" },
  { word: "yogurt", translation: "yogurt" },
  { word: "kefir", translation: "kefir" },
  { word: "cream", translation: "qaymoq" },
  { word: "sour cream", translation: "qatiq" },
  { word: "mayonnaise", translation: "mayonez" },
  { word: "mustard", translation: "xantal" },
  { word: "ketchup", translation: "ketchup" },
  { word: "soy sauce", translation: "sous" },
  { word: "pasta", translation: "makaron" },
  { word: "noodles", translation: "lag'mon" },
  { word: "dumpling", translation: "chuchvara" },
  { word: "pilaf", translation: "osh" },
  { word: "kebab", translation: "kabob" },
  { word: "shashlik", translation: "shashlik" },
  { word: "sandwich", translation: "sendvich" },
  { word: "hamburger", translation: "gamburger" },
  { word: "pizza", translation: "pitsa" },
  { word: "hot dog", translation: "xot-dog" },
  { word: "french fries", translation: "kartoshka fri" },
  { word: "porridge", translation: "kasha" },
  { word: "omelet", translation: "omlet" },
  { word: "pancake", translation: "blin" },
  { word: "donut", translation: "ponchik" },
  { word: "croissant", translation: "kruassan" },
  { word: "baguette", translation: "baget" },
  { word: "toast", translation: "tost" },
  { word: "cereal", translation: "suli yorma" },
  { word: "muesli", translation: "myusli" },
  { word: "popcorn", translation: "popkorn" },
  { word: "word", translation: "so'z" },
  {word: "beach", translation: "sohil"},
  {word: "else", translation: "boshqa"},
  {word: "neat", translation: "tartibli"},
]


function findDuplicateWords(wordsArray) {
  let wordCount = {};
  let duplicates = [];

  // Count occurrences of each word
  wordsArray.forEach((item) => {
    if (wordCount[item.word]) {
      wordCount[item.word]++;
    } else {
      wordCount[item.word] = 1;
    }
  });

  // Find words that appear more than once
  for (let word in wordCount) {
    if (wordCount[word] > 1) {
      duplicates.push(word);
    }
  }

  return duplicates;
}

// Example usagea
let duplicates = findDuplicateWords(words1);
if(duplicates.length != 0){
  console.error("Duplicate words:", duplicates);
}